import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const alamedaData: ServiceArea = {
  slug: "alameda",

  name: "Alameda",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Alameda, CA",

  metaTitle: "E-Waste Recycling in Alameda, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Alameda? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Alameda, CA, helping enterprises, commercial offices, and green-tech companies retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Alameda E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Alameda area. We ensure safe, legal, and professional electronics waste removal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Alameda | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Alameda? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Alameda Premium E-Waste Recycling Solution",

      heroSubheading:
        "We offer reliable e-waste solutions for your enterprise in Alameda, one of the San Francisco Bay Area's premier island cities and thriving business park and technology hub. As a leading service provider, we ensure that each of your electronic devices is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for Alameda's coastal and commercial areas",
          body:
            "The city of Alameda is well known for its historic Naval Air Station, modern redevelopment projects, and growing startup and green-tech companies. Every business and commercial office here needs to constantly upgrade its IT infrastructure and hardware to stay operational. The massive amount of e-waste generated by this rapid technology refresh, if not disposed of properly, can have a serious impact on the environment of this beautiful island and the climate of the Bay Area. In accordance with California's strict e-waste laws, no commercial enterprise can dispose of its old laptops, servers, or monitors in the landfill or trash. Our specialized service ensures that harmful lead, cadmium, and mercury are removed from your equipment and the precious metals are recovered for reuse, helping to increase your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "Corporate data security is a top priority for every enterprise in Alameda. If data is not properly destroyed when recycling old hardware, it can create major legal complications, global compliance violations, and security risks. Currently in California, the Department of Toxic Substances Control (DTSC) imposes strict legal actions and penalties for violating e-waste and data protection regulations. Our industrial-grade data destruction process ensures that each of your storage devices is permanently deleted. We follow the NIST 800-88 standard, an internationally recognized standard. We also provide an official Certificate of Destruction at the end of each project, which proves that your work has been done in a highly secure way, in accordance with California law."
        },
        {
          heading: "Our specialty in corporate IT asset management",
          body:
            "As an experienced service provider, we deeply understand Alameda's local IT market needs and the logistical challenges of its geographic location. Our goal is to offer a transparent and efficient recycling process by reducing business logistical hassles. We not only remove waste, but also help ensure maximum value recovery or ROI of your old assets through refurbishing. Our specialized process presents your business as an 'eco-friendly' brand to investors and conscious customers. By managing e-waste in the right way, on the one hand, your organization's legal and financial risks are greatly reduced, and the system is transparent. We provide customized solutions for everyone, from small marina businesses to large enterprises."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Alameda Recycling?",
          body:
            "We provide reliable and certified recycling services in the Alameda area. Every step of our way is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensuring environmentally friendly and safe recycling in accordance with international standards.",
            "Secure Chain of Custody: Every device's serial number is tracked from collection to destruction.",
            "On-Site & Off-Site Facilities: We can provide direct service to your Alameda office or commercial space depending on your needs.",
            "Zero Landfill Guarantee: We guarantee that no toxic e-waste will end up in a California landfill.",
            "Detailed Compliance Report: We provide full report and destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process",
          body:
            "Our work process is very orderly and transparent which is mainly designed for enterprise level security. First we collect the goods from your Alameda office or data center and prepare a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent to refineries for reuse. At the end of the entire process, we provide you with a final destruction certificate that ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Alameda E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Alameda, CA.",
          qna: [
            {
              question: "Do you accept personal use electronics (B2C) in Alameda?",
              answer:
                "We mainly provide enterprise and commercial services. However, at certain times, we provide B2C (business to consumer) services through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial-grade shredders before recycling in our process, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the call of the hour in a progressive and eco-conscious island like Alameda. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the old technology piled up in your office storeroom today and join us in keeping Alameda's environment cleaner. Our team of experts is always ready to provide customized services for your business. Get your secure recycling quotation today."
        }
      ]
    }
  ]
};