import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const bakersfieldData: ServiceArea = {
  slug: "bakersfield",

  name: "Bakersfield",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Bakersfield, CA",

  metaTitle: "E-Waste Recycling in Bakersfield, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Bakersfield? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Bakersfield, CA, helping enterprises, energy companies, and agro-industrial distribution centers retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Bakersfield E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for business in the Bakersfield area. We ensure safe, legal, and professional electronics waste removal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Bakersfield | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Bakersfield? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Bakersfield Premium E-Waste Recycling Solutions",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise in the city of Bakersfield, one of the main economic drivers of the San Joaquin Valley, the center of oil production, and a large agro-industry. As a leading service provider, we ensure that each of your electronic devices is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable E-Waste Management for Bakersfield's Energy, Agricultural, and Commercial Sectors",
          body:
            "The city of Bakersfield, the center of Kern County, is well known for its oil refineries, large-scale agricultural logistics, manufacturing industry, and fast-growing corporate culture. Every business, energy farm, and commercial distribution center here constantly needs to upgrade IT infrastructure, servers, and technical hardware to keep their operations operational and up-to-date. If the huge amount of e-waste generated by this rapid technology refresh is not properly disposed of, it could have a serious impact on the environment and groundwater levels in the Central Valley. In accordance with California's strict e-waste laws, no commercial company can dispose of its old laptops, servers, networking gear, or monitors in the landfill. Our specialized service ensures that harmful lead, cadmium, and mercury are removed from your company's equipment and the valuable metals are recovered for reuse, increasing your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "Corporate data security is a top priority for every enterprise in Bakersfield. If data is not properly destroyed when recycling old hardware, it can create significant legal complications, corporate compliance violations, and security risks. California's Department of Toxic Substances Control (DTSC) and CalRecycle currently impose strict legal steps and daily fines for violating e-waste and data protection regulations. Stricter rules apply to all electronic devices with built-in or embedded batteries. We follow the NIST 800-88 standard, an internationally recognized standard, and provide an official Certificate of Destruction at the end of each project, which proves that your work has been done in a highly secure manner in accordance with California law."
        },
        {
          heading: "Corporate IT Asset Management and Value Recovery",
          body:
            "As an experienced service provider, we deeply understand the needs of the local IT market in Bakersfield and the logistical challenges of Kern County. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure the highest value recovery or ROI of your old assets by refurbishing them. Our specialized process presents your business as an 'eco-friendly' brand to investors and conscious customers. On the one hand, e-waste management helps to protect the environment. On the other hand, the legal and financial risks of your organization are greatly reduced, and the transparency of the system is maintained. We provide customized solutions for everyone, from small professional firms in Bakersfield to large commercial and industrial enterprises."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Bakersfield Recycling?",
          body:
            "We provide reliable and certified recycling services in the Bakersfield area. Every step of our way is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensuring environmentally friendly and safe recycling in accordance with international standards.",
            "Secure Chain of Custody: Every device's serial number is tracked from collection to destruction.",
            "On-Site and Off-Site Facilities: We can provide direct service to your Bakersfield office or commercial space, depending on your needs.",
            "Zero Landfill Guarantee: We guarantee that no toxic e-waste will end up in a California landfill.",
            "Detailed Compliance Report: We provide a full report and a destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise-level security. First, we collect the goods from your Bakersfield office or industrial infrastructure and create a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent to refineries for reuse. At the end of the entire process, we provide you with a final destruction certificate that ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Bakersfield E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Bakersfield, CA.",
          qna: [
            {
              question: "Do you accept personal use electronics (B2C) in Bakersfield?",
              answer:
                "We mainly provide enterprise and commercial services. However, at certain times, we provide B2C (business to consumer) services through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Before recycling in our process, the data carriers are shredded in an industrial-grade shredder, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the need of the hour in an important, progressive, and dynamic commercial city like Bakersfield. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the old technology in your office storeroom today and join us to make Bakersfield's environment cleaner. Our expert team is always ready to provide customized services tailored to your business needs. Collect your secure recycling quotation today."
        }
      ]
    }
  ]
};