import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const berkeleyData: ServiceArea = {
  slug: "berkeley",

  name: "Berkeley",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Berkeley, CA",

  metaTitle: "E-Waste Recycling in Berkeley, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Berkeley? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Berkeley, CA, helping enterprises, educational institutions, and laboratories retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Berkeley (Berkeley) E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for business in the Berkeley area. We ensure safe, legal, and professional electronics waste removal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Berkeley | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Berkeley? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Berkeley Premium e-waste recycling solution",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise at Berkeley, the East Bay region's leading education, research, and innovation center. As a leading service provider, we guarantee to recycle each of your electronic equipment in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable and Eco-Friendly E-Waste Management for Berkeley Business",
          body:
            "The city of Berkeley is known around the world for its environmental awareness, world-class research institutes, and emerging startup culture. Every business, educational institution, and laboratory here must constantly upgrade its IT infrastructure and electronic equipment to keep its operations up-to-date. The huge amount of e-waste generated by this rapid change, if not disposed of properly, can have a serious impact on the local environment and the ecosystem of the San Francisco Bay Area. California's strict e-waste laws state that a commercial organization cannot dispose of its old laptops, servers, or scientific equipment in landfills with general waste. Our specialized service ensures that harmful lead, mercury, and cadmium are removed from your equipment and valuable materials are recovered for reuse, helping to increase your brand's social and environmental responsibility."
        },
        {
          heading: "Ensuring Secure Data Destruction and Legal Compliance",
          body:
            "Data security is a top priority for every enterprise at Berkeley—especially those dealing with high-level research, legal, or financial information. If data is not destroyed properly when recycling old hardware, it can create significant legal complications, fines, and security risks. Our industrial-grade data destruction process ensures that information on each of your storage devices is permanently erased. We follow the NIST 800-88 standard, which is an internationally recognized standard. In addition, we provide an official certificate of destruction at the end of each project, which proves that your work has been carried out in accordance with California law. This means that your organization's confidentiality is 100% protected, and you are always ready for any audit."
        },
        {
          heading: "Our role in corporate e-waste management",
          body:
            "As an experienced service provider, we deeply understand the needs and institutional challenges of the local IT market in Berkeley. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure the highest value recovery or ROI of your old assets through refurbishing. Our specialized process presents your business as an 'eco-friendly' brand to investors and conscious customers. By managing e-waste in the right way, on the one hand, your organization's legal and financial risks are greatly reduced, and system transparency is maintained."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Berkeley Recycling?",
          body:
            "We provide reliable and certified recycling services in the Berkeley area. Every step of our way is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensures environmentally friendly and safe recycling as per international standards.",
            "Secure Chain of Custody: The serial number of each device is tracked from the time of collection until destruction.",
            "On-Site and Off-Site Facilities: We can provide services directly to your Berkeley office or campus, depending on your needs.",
            "Detailed Compliance Report: We provide comprehensive reports and certificates for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process (Process)",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise-level security. First, we collect the goods from your Berkeley office or organization and prepare a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent to refineries for reuse. At the end of the entire process, we provide you with a final destruction certificate that ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Berkeley E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Berkeley, CA.",
          qna: [
            {
              question: "Do you accept personal use of electronics (B2C) at Berkeley?",
              answer:
                "We primarily serve at the enterprise and commercial levels. However, at certain times, we provide B2C (business to consumer) service through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial-grade shredders before recycling in our process, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the call of the hour in a conscious and progressive city like Berkeley. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the outdated technology in your office storeroom today and join us in keeping Berkeley's environment cleaner. Our expert team is always ready to provide customized services as per your business needs. Collect your secure recycling quotation today."
        }
      ]
    }
  ]
};