import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.png";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const clovisData: ServiceArea = {
  slug: "clovis",

  name: "Clovis",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Clovis, CA",

  metaTitle: "E-Waste Recycling in Clovis, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Clovis? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Clovis, CA, helping enterprises, healthcare centers, and commercial organizations retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Clovis E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Clovis area. We ensure safe, legal, and professional electronics waste removal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Clovis | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Clovis? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Clovis Premium E-Waste Recycling Solution",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise in Clovis, one of Fresno County's fastest growing cities with a unique combination of commercial and residential sectors. As a leading service provider, we ensure that each of your electronic equipment is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for Clovis' progressive business and corporate sector",
          body:
            "The city of Clovis is well known for its excellent quality of life, strong local economy, health care center, and modern corporate culture. Every business, doctor's chamber, school, and commercial organization here is constantly upgrading their IT infrastructure and hardware to keep their daily operations and data systems up to date. The large amount of e-waste generated by this rapid technology refresh can have a serious impact on the environment of this region of the Central Valley if not disposed of properly. According to California's strict e-waste laws, no commercial organization can dispose of their old laptops, servers, networking gear, or monitors in the landfill with general garbage. Our specialized service ensures that harmful chemicals are removed from your company's equipment and valuable metals are recovered for reuse, helping to increase your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "Corporate data security is a top priority for every enterprise in Clovis. If data is not properly destroyed when recycling old hardware, it can create significant legal complications, corporate compliance violations, and security risks. Violations of e-waste and data protection regulations in California are currently subject to strict legal action and daily enforcement by the Department of Toxic Substances Control (DTSC) and CalRecycle. In particular, stricter regulations apply to all electronic devices with built-in or embedded batteries. We follow the NIST 800-88 standard, an internationally recognized standard, for every project's destruction, which proves that your work has been done in a highly secure manner in accordance with California law."
        },
        {
          heading: "Our specialty in corporate IT asset management",
          body:
            "As an experienced service provider, we deeply understand the needs of the local IT market in Clovis and the logistical challenges of Fresno County. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure the highest value recovery or ROI of your old assets through refurbishing. Our specialized process presents your business as an 'eco-friendly' brand to investors and conscious customers. By managing e-waste in the right way, on the one hand, the legal and financial risks of your organization are greatly reduced, and the system is transparent. We provide customized solutions for everyone, from small professional firms to large commercial enterprises."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Clovis Recycling?",
          body:
            "We provide reliable and certified recycling services in the Clovis area. Every step of our way is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensuring environmentally friendly and safe recycling in accordance with international standards.",
            "Secure Chain of Custody: Every device's serial number is tracked from collection to destruction.",
            "On-Site & Off-Site Facilities: We can provide direct service to your Clovis office or commercial space, depending on your needs.",
            "Detailed Compliance Report: We provide a full report and destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise-level security. First, we collect the goods from your Clovis office or data center and prepare a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent to refineries for reuse. At the end of the entire process, we provide you with a final destruction certificate that ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Clovis E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Clovis, CA.",
          qna: [
            {
              question: "Do you accept personal use of electronics (B2C) in Clovis?",
              answer:
                "We mainly provide enterprise and commercial services. However, at certain times, we provide B2C (business to consumer) services through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial-grade shredders before recycling in our process, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the call of the hour in a progressive and well-planned commercial city like Clovis. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the old technologies piling up in your office storeroom today and join us in making Clovis a cleaner environment. Our expert team is always ready to provide customized services tailored to your business needs. Collect your secure recycling quotation today."
        }
      ]
    },
    {
      slug: "electronics-recycling",
      title: "Electronics Recycling in Clovis",
      shortDescription:
        "Certified electronics recycling and ITAD in Clovis, CA. R2v3 and ISO-certified, NIST 800-88 data destruction, and full chain-of-custody.",
      icon: "Recycle",
      metaTitle:
        "Electronics Recycling in Clovis, CA | Certified ITAD & Data Destruction | Integritrade",
      metaDescription:
        "Certified electronics recycling & ITAD in Clovis, CA. R2v3 & ISO-certified, NIST 800-88 data destruction, full chain-of-custody. Schedule a secure pickup.",
      image: electronicRecycling,
      heroHeading:
        "Certified Electronics Recycling in Clovis: Protect Your Data and the Environment",
      heroSubheading:
        "For Clovis businesses retiring old IT assets and electronic equipment, responsible disposal is both a security obligation and an environmental one. Whether you are clearing out a back-office storeroom, retiring aging workstations, or planning a larger equipment refresh, partnering with a certified electronics recycler in Clovis protects your data, your compliance standing, and the Central Valley environment.",
      ctaText: "Get a Free Quote",
      details: [
        {
          heading: "What Clovis Businesses Should Look For in a Recycler",
          body:
            "As a fast-growing community right next to Fresno, Clovis is home to a mix of healthcare practices, professional firms, retailers, and agribusiness operations, all of which generate retired technology that has to be handled securely. Improper disposal of electronics not only harms the environment but also exposes your organization to serious data breach risks and regulatory penalties. In this guide, we explain how to choose a proper electronics recycling firm, why industry certifications are critical, and why Integritrade is the trusted, locally based choice for secure, compliant, and sustainable IT Asset Disposition (ITAD) and electronics recycling."
        },
        {
          heading: "The Hidden Dangers of Using an Uncertified Recycler",
          body:
            "Many businesses in Clovis mistakenly assume that any local e-waste recycler will handle their retired devices responsibly. Unfortunately, the electronics recycling industry includes many uncertified operators who use substandard destruction methods. Handing your sensitive equipment over to an uncertified vendor can lead to serious consequences:",
          bullets: [
            "Data Breaches: Without rigorous, documented data destruction protocols, sensitive information left on hard drives, servers, and even printers can be recovered and exploited.",
            "Environmental Harm: Uncertified vendors often export hazardous e-waste to developing nations or use improper processing methods that release toxic heavy metals into the local environment.",
            "Compliance Failures: Organizations subject to HIPAA, FACTA, or corporate governance standards require unbroken chain-of-custody documentation. Uncertified recyclers rarely provide the audit-ready reporting necessary to prove compliance."
          ]
        },
        {
          heading: "Certifications: Your First Line of Defense",
          body:
            "When evaluating electronics recycling in Clovis, the most important factor to look for is third-party certification. The U.S. Environmental Protection Agency (EPA) strongly encourages businesses to use certified electronics recyclers, specifically recognizing the Responsible Recycling (R2) standard. The R2 standard, currently in its rigorous R2v3 iteration, is the premier global certification for electronics reuse and recycling. According to the EPA, certified recyclers have demonstrated through independent audits that they maximize reuse, minimize environmental exposure, ensure safe downstream management, and require the complete destruction of all data on used electronics. When a facility is R2v3 certified, it means their entire process, from the moment an asset leaves your Clovis location to its final disposition, is heavily regulated, tracked, and audited."
        },
        {
          heading: "The Integritrade Difference for Clovis",
          body:
            "While some of the largest national electronics recycling corporations focus primarily on high-volume commodity processing, businesses in Clovis often require a more tailored, accountable, and transparent approach to their ITAD needs. Headquartered just next door in Fresno and serving the entire Central Valley, including Clovis, Madera, and Visalia, Integritrade provides enterprise-grade security and compliance without treating your organization like just another number on a spreadsheet. We hold a comprehensive suite of the industry's most demanding certifications:",
          bullets: [
            "R2v3 Certified: Guaranteeing the highest standards in environmental responsibility, data security, and downstream accountability.",
            "ISO 14001 (Environmental Management): Ensuring sustainable operations that minimize environmental footprint.",
            "ISO 27001 (Information Security Management): Providing globally recognized frameworks for keeping your sensitive data secure throughout the disposition process.",
            "ISO 45001 (Occupational Health & Safety): Demonstrating a commitment to safe facility operations.",
            "ISO 9001 (Quality Management): Ensuring consistent, high-quality service delivery and reporting."
          ]
        },
        {
          heading: "How Integritrade Goes Beyond Basic Recycling",
          body:
            "Integritrade differentiates itself by focusing on what truly matters to businesses managing risk: absolute certainty.",
          bullets: [
            "Unbroken Chain of Custody: We provide serialized accountability from your loading dock in Clovis to the downstream processor. For ITAD projects, every asset is scanned, with no black boxes in the audit trail.",
            "100% Data Destruction Guarantee: Whether you require NIST 800-88 compliant wiping, 2mm physical shredding, or videotaped destruction, our data destruction services are built to withstand rigorous audits.",
            "Comprehensive Reporting: We provide serialized Certificates of Destruction, remarketing reports, and R2v3 recycling documentation, the exact proof your compliance officers need.",
            "Value Recovery: For newer assets, our Full ITAD Package includes refurbishment and remarketing, letting your organization recover financial value through revenue splits or upfront buybacks.",
            "Background-Checked Personnel: Your sensitive assets are handled exclusively by verified professionals in our 24/7 video-monitored facility."
          ]
        },
        {
          heading: "Complete Recycling & ITAD Solutions in Clovis",
          body:
            "Whether your organization needs Basic Recycling for previously sanitized equipment, compliance-grade Data Destruction, or a Full ITAD Package with value recovery, Integritrade has a tailored solution. We even offer Demanufacturing & Prototype Destruction for highly sensitive intellectual property that must be physically destroyed with witnessed oversight. Don't leave your data security and environmental compliance to chance with uncertified vendors. Choose the certified, secure, and accountable partner for electronics recycling in Clovis."
        },
        {
          heading: "Clovis Electronics Recycling: Frequently Asked Questions",
          body:
            "Here are some common questions Clovis businesses ask about certified electronics recycling and data destruction.",
          qna: [
            {
              question: "Is deleting files or factory-resetting a device enough before recycling?",
              answer:
                "No. Deleted or reset data can often be recovered with forensic tools. We use NIST 800-88 compliant wiping or physical shredding so data is permanently unrecoverable."
            },
            {
              question: "Do you provide proof of recycling and data destruction?",
              answer:
                "Yes. Every project includes a serialized Certificate of Destruction and R2v3 recycling documentation for your audit and compliance records."
            },
            {
              question: "What types of electronics do you accept from Clovis businesses?",
              answer:
                "We handle computers, laptops, servers, networking gear, monitors, printers, hard drives, SSDs, mobile devices, and most other business IT hardware."
            },
            {
              question: "Do you offer on-site pickup in Clovis?",
              answer:
                "Yes. We schedule secure, chain-of-custody pickups directly from your Clovis location, and can provide a free site walkthrough for larger projects."
            }
          ]
        }
      ]
    }
  ]
};