import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.png";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const clovisData: ServiceArea = {
  slug: "clovis",

  name: "Clovis",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Clovis, CA",

  metaTitle: "E-Waste Recycling in Clovis, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Clovis? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Clovis, CA, helping enterprises, healthcare centers, and commercial organizations retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Clovis E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Clovis area. We ensure safe, legal, and professional electronics waste removal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Clovis | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Clovis? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Clovis Premium E-Waste Recycling Solution",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise in Clovis, one of Fresno County's fastest growing cities with a unique combination of commercial and residential sectors. As a leading service provider, we ensure that each of your electronic equipment is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for Clovis' progressive business and corporate sector",
          body:
            "The city of Clovis is well known for its excellent quality of life, strong local economy, health care center, and modern corporate culture. Every business, doctor's chamber, school, and commercial organization here is constantly upgrading their IT infrastructure and hardware to keep their daily operations and data systems up to date. The large amount of e-waste generated by this rapid technology refresh can have a serious impact on the environment of this region of the Central Valley if not disposed of properly. According to California's strict e-waste laws, no commercial organization can dispose of their old laptops, servers, networking gear, or monitors in the landfill with general garbage. Our specialized service ensures that harmful chemicals are removed from your company's equipment and valuable metals are recovered for reuse, helping to increase your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "Corporate data security is a top priority for every enterprise in Clovis. If data is not properly destroyed when recycling old hardware, it can create significant legal complications, corporate compliance violations, and security risks. Violations of e-waste and data protection regulations in California are currently subject to strict legal action and daily enforcement by the Department of Toxic Substances Control (DTSC) and CalRecycle. In particular, stricter regulations apply to all electronic devices with built-in or embedded batteries. We follow the NIST 800-88 standard, an internationally recognized standard, for every project's destruction, which proves that your work has been done in a highly secure manner in accordance with California law."
        },
        {
          heading: "Our specialty in corporate IT asset management",
          body:
            "As an experienced service provider, we deeply understand the needs of the local IT market in Clovis and the logistical challenges of Fresno County. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure the highest value recovery or ROI of your old assets through refurbishing. Our specialized process presents your business as an 'eco-friendly' brand to investors and conscious customers. By managing e-waste in the right way, on the one hand, the legal and financial risks of your organization are greatly reduced, and the system is transparent. We provide customized solutions for everyone, from small professional firms to large commercial enterprises."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Clovis Recycling?",
          body:
            "We provide reliable and certified recycling services in the Clovis area. Every step of our way is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensuring environmentally friendly and safe recycling in accordance with international standards.",
            "Secure Chain of Custody: Every device's serial number is tracked from collection to destruction.",
            "On-Site & Off-Site Facilities: We can provide direct service to your Clovis office or commercial space, depending on your needs.",
            "Detailed Compliance Report: We provide a full report and destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise-level security. First, we collect the goods from your Clovis office or data center and prepare a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent to refineries for reuse. At the end of the entire process, we provide you with a final destruction certificate that ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Clovis E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Clovis, CA.",
          qna: [
            {
              question: "Do you accept personal use of electronics (B2C) in Clovis?",
              answer:
                "We mainly provide enterprise and commercial services. However, at certain times, we provide B2C (business to consumer) services through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial-grade shredders before recycling in our process, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the call of the hour in a progressive and well-planned commercial city like Clovis. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the old technologies piling up in your office storeroom today and join us in making Clovis a cleaner environment. Our expert team is always ready to provide customized services tailored to your business needs. Collect your secure recycling quotation today."
        }
      ]
    }
  ]
};