import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const emeryvilleData: ServiceArea = {
  slug: "emeryville",

  name: "Emeryville",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Emeryville, CA",

  metaTitle: "E-Waste Recycling in Emeryville, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Emeryville? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Emeryville, CA, helping enterprises, biotech laboratories, and commercial establishments retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Emeryville E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Emeryville area. We ensure safe, legal, and professional electronics waste removal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Emeryville | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Emeryville? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Emeryville Premium E-Waste Recycling Solutions",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise in Emeryville, one of the leading business, biotech, and commercial hubs of the East Bay region. As a leading service provider, we ensure that each of your electronic devices is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for Emeryville's dynamic businesses",
          body:
            "The city of Emeryville is small in size, but its economic importance is immense. It is the center of world-renowned animation studios, biotech laboratories, and numerous retail and technology establishments. Every business and corporate office here needs to constantly refresh its IT infrastructure and hardware to keep its operations up and running. The large amount of e-waste generated by this rapid change, if not disposed of properly, is detrimental to the local environment and the ecosystem of the San Francisco Bay Area. In accordance with California's strict e-waste laws, no commercial company can dispose of its old laptops, servers, or monitors in landfills. Our specialized service ensures that harmful chemicals are removed from your company's equipment and valuable metals are recovered for reuse, helping to increase your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "Corporate data security or information privacy is a top priority for every enterprise in Emeryville. If data is not properly destroyed when recycling old hardware, it can create significant legal complications, fines, and security risks. Violations of current e-waste and data protection regulations in California can result in severe legal action and fines from the Department of Toxic Substances Control (DTSC). Our industrial-grade data destruction process ensures that each of your storage devices is permanently deleted. We follow the NIST 800-88 standard, an internationally recognized standard. We also provide an official Certificate of Destruction at the end of each project, which proves that your work has been done in a highly secure way, in accordance with California law."
        },
        {
          heading: "Our Specialties in Corporate IT Asset Management",
          body:
            "As an experienced service provider, we deeply understand the needs of the local IT market in Emeryville and the logistical challenges faced by tech and biotech companies. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure maximum value recovery or ROI for your old assets through refurbishing. Our specialized process brands your business as an 'Eco-Friendly' brand, helping to present it to investors and conscious customers. On the one hand, e-waste management protects the environment, and on the other hand, the legal and financial risks of your organization are greatly reduced. We provide customized solutions for everyone, from small startups to large enterprises, in Emeryville."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Emeryville Recycling?",
          body:
            "We provide reliable and certified recycling services in the Emeryville area. Every step of our way is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensures environmentally friendly, safe recycling in accordance with international standards.",
            "Secure Chain of Custody: The serial number of each device is tracked from collection through destruction.",
            "On-Site & Off-Site Facilities: We can provide direct service to your Emeryville office or lab, depending on your needs.",
            "ZERO LANDFILL GUARANTEE: We guarantee that no toxic e-waste will end up in a California landfill.",
            "Detailed Compliance Report: We provide full report and destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process (Process)",
          body:
            "Our work process is very orderly and transparent which is mainly designed for enterprise level security. First we collect the goods from your Emeryville office or data center and prepare a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass and metal components. Finally, precious metals such as copper and gold are sent to refineries for reuse. At the end of this whole process we provide you with a final destruction certificate which ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Emeryville E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Emeryville, CA.",
          qna: [
            {
              question: "Do you accept personal use electronics (B2C) in Emeryville?",
              answer:
                "We primarily serve at the enterprise and commercial levels. However, at certain times we provide B2C (business to consumer) service through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial grade shredders before recycling in our process and we provide guarantee certificate for this which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the call of the hour in a fast-growing and modern commercial city like Emeryville. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the outdated technology in your office storeroom today and join us in keeping Emeryville's environment cleaner. Our expert team is always ready to provide customized services as per your business needs. Collect your secure recycling quotation today."
        }
      ]
    }
  ]
};