import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const fosterCityData: ServiceArea = {
  slug: "foster-city",

  name: "Foster City",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Foster City, CA",

  metaTitle: "E-Waste Recycling in Foster City, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Foster City? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Foster City, CA, helping enterprises, software companies, and corporate offices retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Foster City E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Foster City area. We ensure safe, legal, and professional electronics waste disposal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Foster City | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Foster City? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Foster City Premium E-Waste Recycling Solution",

      heroSubheading:
        "We offer reliable e-waste solutions for your enterprise in Foster City, one of San Mateo County's premier planned commercial and tech hubs. As a leading service provider, we guarantee to recycle each of your electronic equipment in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for Foster City businesses",
          body:
            "Foster City is well-known for its beautiful landscape and modern IT infrastructure, which is a top choice for many global software and fintech companies. Every business and corporate office here needs to constantly update hardware and networking systems to keep them running. The huge amount of e-waste generated by this rapid change can adversely affect the environment of the Bay Area if not disposed of properly. California's strict e-waste law states that no commercial company can dispose of their old laptops, servers, or monitors in landfills with general waste. Our specialized service ensures that harmful chemicals are removed from your company's equipment and valuable metals are recovered for reuse, helping to increase your brand's social and environmental responsibility."
        },
        {
          heading: "Ensuring Secure Data Destruction and Legal Compliance",
          body:
            "Data security or information privacy is a top priority for every enterprise in Foster City. If data is not properly destroyed when recycling old hardware, it can create major legal complications, fines, and security risks. Our industrial-grade data destruction process ensures that information on each of your storage devices is permanently deleted. We follow the NIST 800-88 standard, which is an internationally recognized, highly secure standard. Additionally, at the end of each project, we provide an official Certificate of Destruction, which proves that your work has been done very securely in accordance with California law. It keeps your organization's confidentiality 100% protected, and you are always prepared for any audit."
        },
        {
          heading: "Our specialty in corporate e-waste management",
          body:
            "As an experienced service provider, we deeply understand the needs and challenges of the local IT market in Foster City. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure maximum value recovery or ROI for your old assets by refurbishing them. Our specialized process helps you present your business as an 'eco-friendly' brand to investors. Managing e-waste the right way not only protects the environment but also greatly reduces your organization's legal and financial risks and maintains system transparency. We provide customized solutions for everyone, from small startups to large corporations in Foster City."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Foster City Recycling?",
          body:
            "We provide reliable and certified recycling services in the Foster City area. Every step of our way is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensures environmentally friendly and safe recycling as per international standards.",
            "Secure Chain of Custody: The serial number of each device is tracked from the time of collection until destruction.",
            "On-Site and Off-Site Facilities: We can also provide direct service to your Foster City office as per your needs.",
            "Zero Landfill Guarantee: We guarantee that no toxic e-waste will end up in a California landfill.",
            "Detailed Compliance Report: We provide comprehensive reports and certificates for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process (Process)",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise-level security. First, we collect the goods from your Foster City office or data center and prepare a full audit report on them. Then the data carriers (HDD/SSD) from each device are separated and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent to refineries for reuse. At the end of this whole process, we provide you with a final destruction certificate, which ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Foster City E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Foster City, CA.",
          qna: [
            {
              question: "Do you accept personal use electronics (B2C) in Foster City?",
              answer:
                "We primarily serve at the enterprise and commercial levels. However, at certain times, we provide B2C (business to consumer) service through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial-grade shredders before recycling in our process, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the call of the hour in a modern and technology-driven city like Foster City. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the outdated technology in your office storeroom today and join us in keeping Foster City's environment cleaner. Our team of experts is always ready to provide customized services as needed. Get your secure recycling quotation today and move towards a sustainable future."
        }
      ]
    }
  ]
};