import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const mercedData: ServiceArea = {
  slug: "merced",

  name: "Merced",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Merced, CA",

  metaTitle: "E-Waste Recycling in Merced, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Merced? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Merced, CA, helping enterprises, educational institutions, and agricultural processing centers retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Merced E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Merced area. We ensure safe, legal, and professional electronics waste removal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Merced | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Merced? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Merced Premium E-waste Recycling Solution",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise in the fast-growing education, technology, and agriculture hub of Merced, benefiting UC Merced and emerging tech-research. As a leading service provider, we ensure that each of your electronic equipment is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for Merced's education, agri-tech and emerging commercial sectors",
          body:
            "The city of Merced, known as the 'Gateway to Yosemite' in the Central Valley, is now not only an agricultural region, but has become a modern research and institutional hub. Every business, educational institution, and agricultural processing center here has to constantly upgrade IT infrastructure and high-end networking devices to keep up with their operational dedication and data backbone. The large amount of e-waste generated by this rapid technology refresh, if not disposed of properly, can have a serious impact on the Central Valley's sensitive ecosystems and valuable groundwater. According to California's strict e-waste laws, no commercial company can dispose of their old laptops, servers, networking gear, or monitors in landfills. Our specialized service ensures that harmful lead, lithium, and other heavy metals are removed from your company's equipment and valuable materials are recovered for reuse, which helps increase your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "Corporate data security or the privacy of proprietary information is a top priority for every enterprise and research institute in Merced. If data is not properly destroyed when recycling old hardware, it can create significant legal complications, corporate compliance violations, and security risks. In California, violations of e-waste and data protection regulations currently result in the Department of Toxic Substances Control (DTSC) and CalRecycle imposing strict legal measures and daily fines. In particular, stricter regulations apply to all electronic devices with built-in or embedded batteries. We follow the NIST 800-88 standard, an internationally recognized standard. We also provide an official Certificate of Destruction at the end of each project, which proves that your work was completed safely in compliance with California law."
        },
        {
          heading: "Corporate IT Asset Management and Value Recovery",
          body:
            "As an experienced service provider, we deeply understand the needs of the local IT market in Merced and the logistics challenges of the San Joaquin Valley. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure maximum value recovery or ROI for your old assets through refurbishing. Our specialized process presents your business as an 'eco-friendly' brand to investors and conscious customers. On the one hand, e-waste management protects the environment, and on the other hand, the legal and financial risks of your organization are greatly reduced. We provide customized solutions for everyone, from small professional startups to large commercial, institutional, and industrial enterprises."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Merced Recycling?",
          body:
            "We provide reliable and certified recycling services in the Merced area. Every step of our way is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensures environmentally friendly and safe recycling as per international standards.",
            "Secure Chain of Custody: The serial number of each device is tracked from the time of collection until destruction.",
            "On-Site and Off-Site Facilities: We can provide direct service to your Merced office or commercial space as per your requirement.",
            "Zero Landfill Guarantee: We guarantee that no toxic e-waste will end up in a California landfill.",
            "Detailed Compliance Report: We provide a full report and a destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise-level security. First, we collect the goods from your Merced office or institutional infrastructure and prepare a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent back to the refinery for reuse. At the end of this whole process, we provide you with a final destruction certificate that ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Merced E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Merced, CA.",
          qna: [
            {
              question: "Do you accept personal use of electronics (B2C) at Merced?",
              answer:
                "We primarily serve at the enterprise and commercial levels. However, at certain times, we provide B2C (business to consumer) service through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial-grade shredders before recycling in our process, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the call of the hour in a fast-growing education and modern commercial city like Merced. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the outdated technology in your office storeroom today and join us in keeping Merced's environment cleaner. Our team of experts is always ready to provide customized service to your business needs. Collect your secure recycling quotation today."
        }
      ]
    }
  ]
};