import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.png";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const modestoData: ServiceArea = {
  slug: "modesto",

  name: "Modesto",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Modesto, CA",

  metaTitle: "E-Waste Recycling in Modesto, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Modesto? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Modesto, CA, helping enterprises, food processing plants, and manufacturing businesses retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Modesto E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Modesto area. We ensure safe, legal, and professional electronics waste disposal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Modesto | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Modesto? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Modesto Premium E-waste Recycling Solution",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise in the city of Modesto, the heart of Stanislaus County, one of the leading hubs of agro-technology and manufacturing industries. As a leading service provider, we ensure that each of your electronic devices is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for Modesto's Agri-Business, Manufacturing and Commercial Sectors",
          body:
            "Modesto, one of the Central Valley's premier economic regions, is renowned for its world-class agricultural processing, wine production, and distribution network. Every business, food processing plant, and corporate office here requires constant IT infrastructure and technical hardware upgrades to maintain their operational dynamism. The vast amount of e-waste generated by this rapid technology refresh, if not properly disposed of, can harm the region's fertile farmland and have a serious impact on groundwater levels. In accordance with California's strict e-waste laws, no commercial company can dispose of its old laptops, servers, networking gear, or monitors in landfills. Our specialized service ensures that harmful lead, mercury, and other toxic elements are removed from your company's equipment and that valuable metals are recovered for reuse, increasing your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "Corporate data security is a top priority for every enterprise at Modesto. If data is not properly destroyed when recycling old hardware, it can create significant legal complications, corporate compliance violations, and security risks. Violations of e-waste and data protection regulations in California currently draw stricter legal action and daily fines from the Department of Toxic Substances Control (DTSC) and CalRecycle, especially for all electronic devices with built-in or embedded batteries. We follow the NIST 800-88 standard, an internationally recognized standard, and provide an official Certificate of Destruction, which proves that your work was done in a highly secure manner in accordance with California law."
        },
        {
          heading: "Corporate IT Asset Management and Value Recovery",
          body:
            "As an experienced service provider, we deeply understand the needs of the local IT market in Modesto and the logistics challenges of Stanislaus County. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure the highest value recovery or ROI of your old assets through refurbishing. Our specialized process presents your business as an 'eco-friendly' brand to investors and conscious customers. On the one hand, e-waste management protects the environment, and on the other hand, your organization's legal and financial risks are greatly reduced. We provide customized solutions for everyone, from small professional firms in Modesto to large commercial and industrial enterprises."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Modesto Recycling?",
          body:
            "We provide reliable and certified recycling services in the Modesto area. Every step of our way is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensures environmentally friendly and safe recycling as per international standards.",
            "Secure Chain of Custody: The serial number of each device is tracked from the time of collection until destruction.",
            "On-Site & Off-Site Facilities: We can provide direct service to your Modesto office or commercial space, depending on your needs.",
            "Detailed Compliance Report: We provide a full report and a destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise-level security. First, we collect the goods from your Modesto office or processing center and prepare a full audit report on them. Then the data carriers (HDD/SSD) from each device are separated and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent to the refinery for reuse. At the end of this whole process, we provide you with a final destruction certificate, which ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Modesto E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Modesto, CA.",
          qna: [
            {
              question: "Do you accept personal use electronics (B2C) in Modesto?",
              answer:
                "We primarily serve at the enterprise and commercial levels. However, at certain times, we provide B2C (business to consumer) service through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial-grade shredders before recycling in our process, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the call of the hour in an important agri-industrial center and thriving commercial city like Modesto. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC provides you with the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the outdated technology in your office storeroom today and join us in keeping Modesto's environment cleaner. Our expert team is always ready to provide customized services according to your business needs. Collect your secure recycling quotation today."
        }
      ]
    }
  ]
};