import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const oaklandData: ServiceArea = {
  slug: "oakland",

  name: "Oakland",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Oakland, CA",

  metaTitle: "E-Waste Recycling in Oakland, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Oakland? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Oakland, CA, helping enterprises and logistics firms retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Oakland (Oakland) E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Oakland area. We ensure safe, legal, and professional electronics waste removal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Oakland | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Oakland? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Oakland (Oakland) Premium E-waste Recycling Solution",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise in Oakland, one of the leading commercial and logistics hubs in the San Francisco Bay Area. As a leading service provider, we ensure that each of your electronic devices is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for Auckland's growing businesses.",
          body:
            "The city of Oakland is known for its diverse economic structure, global shipping port, and fast-growing commercial sector. Every business organization and logistics firm here needs to constantly upgrade its IT infrastructure and hardware to maintain its performance. The massive amount of e-waste generated by this rapid technology refresh can have an adverse impact on the local environment and the Bay Area's climate if not properly disposed of. In accordance with California's strict e-waste laws (which have recently been expanded), no commercial company can dispose of their old laptops, servers, or monitors in landfills with general garbage. Our specialized service ensures that harmful lead and mercury are removed from your company's equipment and precious metals are recovered for reuse, helping to increase your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "Corporate data security or information privacy is a top priority for every enterprise in Oakland. If data is not destroyed properly when recycling old hardware, it can create significant legal complications, fines, and security risks. In California, DTSC currently imposes severe penalties for violating e-waste regulations. Our industrial-grade data destruction process ensures that data on each of your storage devices is permanently deleted. We follow the NIST 800-88 standard, which is an internationally recognized standard. We also provide an official certificate of destruction at the end of each project, which proves that your work has been done in a highly secure way, in accordance with California law. This keeps your organization confidential and ready for any audit."
        },
        {
          heading: "Our Specialties in Corporate IT Asset Management",
          body:
            "As an experienced service provider, we deeply understand the needs of the local IT market in Auckland and the logistical challenges as a port city. We aim to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure maximum value recovery or ROI of your old assets through refurbishing. Our specialized process makes your business an 'Eco-Friendly' brand for investors and conscious customers. Helping to present. On the one hand, e-waste management protects the environment, and on the other hand, the legal and financial risks of your organization are greatly reduced. We provide customized solutions for everyone, from small startups to large enterprises in Oakland."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Oakland Recycling?",
          body:
            "We provide reliable and certified recycling services in the Oakland area. Every step of our way is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensures environmentally friendly and safe recycling as per international standards.",
            "Secure Chain of Custody: The serial number of each device is tracked from the time of collection until destruction.",
            "ON-SITE & OFF-SITE FACILITIES: We can provide direct service to your Oakland office or downtown workspace, depending on your needs.",
            "Detailed Compliance Report: We provide a full report and a destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process (Process)",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise-level security. First, we collect the goods from your Oakland office or data center and prepare a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent to refineries for reuse. At the end of this entire process,s we provide you with a Final Destruction Certificate,e which ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Oakland E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Oakland, CA.",
          qna: [
            {
              question: "Do you accept personal use of electronics (B2C) in Oakland?",
              answer:
                "We primarily serve at the enterprise and commercial levels. However, at certain times, we provide B2C (business to consumer) service through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial-grade shredders before recycling in our process, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the call of the hour in a progressive and dynamic commercial city like Oakland. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the outdated technology in your office storeroom today and join us in keeping Oakland's environment cleaner. Our team of experts is always ready to provide customized service to your business needs. Collect your secure recycling quotation today."
        }
      ]
    },
    {
      slug: "data-destruction-services",

      title: "Oakland Certified Data Destruction | Secure Hard Drive & Data Disposal",

      shortDescription:
        "Certified data destruction services for businesses in Oakland. Secure data wiping, hard drive destruction, NIST 800-88 compliant processes, and complete compliance documentation.",

      icon: "Shield",

      metaTitle:
        "Certified Data Destruction Oakland | Secure Hard Drive Destruction Services",

      metaDescription:
        "Looking for certified data destruction in Oakland, CA? IntegriTrade LLC provides secure data wiping, hard drive destruction, NIST 800-88 compliant sanitization, and Certificates of Destruction for businesses.",

      image: dataDestruction,

      heroHeading:
        "Oakland Certified Data Destruction Services",

      heroSubheading:
        "Protect your organization from data breaches, compliance violations, and security risks through certified data destruction and secure media disposal services.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading:
            "Protect Sensitive Information Before Technology Leaves Your Organization",
          body:
            "Organizations throughout Oakland rely on technology to store, process, and manage sensitive information every day. Healthcare providers, logistics companies, government agencies, educational institutions, manufacturers, technology firms, and professional service organizations maintain critical data across computers, servers, storage systems, mobile devices, and backup media. These systems often contain customer records, employee information, financial documents, healthcare data, intellectual property, contracts, operational records, and confidential business communications. When technology assets reach end-of-life, the information stored on them remains vulnerable if not properly destroyed. Simply deleting files or formatting storage devices does not permanently remove data. Certified data destruction ensures sensitive information is permanently eliminated before assets are reused, sold, recycled, or disposed of."
        },
        {
          heading:
            "Why Certified Data Destruction Matters in Oakland",
          body:
            "Businesses and organizations in Oakland face increasing cybersecurity, privacy, and regulatory compliance requirements. A data breach involving retired technology assets can result in financial losses, legal liability, regulatory penalties, operational disruption, and reputational harm. Organizations must demonstrate that confidential information has been securely destroyed throughout the technology lifecycle. Certified data destruction provides documented proof that data has been permanently removed, helping organizations reduce risk while supporting compliance, governance, and cybersecurity objectives."
        },
        {
          heading: "Our Secure Data Destruction Process",
          body:
            "IntegriTrade LLC follows strict security procedures designed to ensure complete and verifiable destruction of sensitive information. Every project begins with secure collection and transportation of data-bearing assets. Devices are tracked through documented chain-of-custody procedures and processed using NIST 800-88 compliant sanitization methods. For organizations requiring physical destruction, we provide hard drive shredding and media destruction services that permanently eliminate the possibility of data recovery. Every stage of the process is documented to ensure accountability, transparency, and confidence.",
          bullets: [
            "Secure collection and transportation",
            "Documented chain-of-custody tracking",
            "NIST 800-88 compliant data sanitization",
            "Hard drive and SSD destruction services",
            "Certificates of Destruction (COD)",
            "Detailed audit and compliance reporting"
          ]
        },
        {
          heading: "What Types of Media Can Be Destroyed?",
          body:
            "Our certified data destruction services support a wide range of storage media including hard drives, solid-state drives (SSD), backup tapes, storage arrays, USB flash drives, memory cards, laptops, desktop computers, servers, healthcare technology systems, manufacturing technology equipment, mobile devices, engineering workstations, and enterprise storage infrastructure. Whether your organization needs to destroy a handful of storage devices or manage a large-scale technology retirement project, we provide scalable destruction solutions tailored to your operational and security requirements."
        },
        {
          heading: "Compliance, Security, and Risk Reduction",
          body:
            "Proper data destruction is a critical component of modern cybersecurity and risk management programs. Organizations must ensure retired storage devices cannot be used to recover confidential information. Our certified destruction process helps organizations demonstrate compliance during audits, reduce exposure to data theft, and support internal governance initiatives. By ensuring information is permanently removed before assets leave your control, organizations can significantly reduce future security and compliance risks. Every completed project includes official documentation verifying destruction according to recognized industry standards."
        },
        {
          heading:
            "Why Choose IntegriTrade LLC for Data Destruction?",
          body:
            "Organizations throughout Oakland trust IntegriTrade LLC because we provide secure, transparent, and fully documented destruction services. Our team understands the unique security requirements of healthcare providers, logistics companies, government agencies, educational institutions, technology firms, manufacturers, and enterprise businesses. We deliver customized solutions designed to protect sensitive information while ensuring compliance and operational efficiency.",
          bullets: [
            "NIST 800-88 compliant destruction processes",
            "Certified destruction documentation",
            "Secure chain-of-custody procedures",
            "Experienced data security specialists",
            "Flexible on-site and off-site solutions",
            "Trusted by healthcare, logistics, government, education, and enterprise organizations"
          ]
        },
        {
          heading: "Common Questions About Data Destruction",
          body:
            "Find answers to frequently asked questions about certified data destruction services in Oakland.",
          qna: [
            {
              question:
                "Is deleting files enough to protect sensitive information?",
              answer:
                "No. Deleted files can often be recovered using specialized software. Certified data destruction permanently removes information and prevents future recovery."
            },
            {
              question: "What is NIST 800-88?",
              answer:
                "NIST 800-88 is a widely recognized media sanitization standard that outlines approved methods for permanently removing data from storage devices."
            },
            {
              question:
                "Do you provide Certificates of Destruction?",
              answer:
                "Yes. We provide official Certificates of Destruction (COD) and supporting documentation for completed projects."
            },
            {
              question:
                "Can SSDs and hard drives both be destroyed?",
              answer:
                "Yes. We securely process hard drives, SSDs, backup media, storage arrays, and other data-bearing devices."
            },
            {
              question:
                "Do you support enterprise and multi-location destruction projects?",
              answer:
                "Absolutely. We support projects ranging from small office device disposal to large-scale healthcare technology upgrades, government office refreshes, facility relocations, manufacturing technology replacements, and enterprise-wide technology refresh initiatives."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Protecting sensitive information does not end when technology reaches the end of its useful life. IntegriTrade LLC provides certified data destruction services in Oakland that help organizations eliminate data security risks, maintain compliance, and safeguard valuable information. Whether you require secure data wiping, hard drive destruction, or complete media disposal services, our team delivers trusted solutions designed to keep your organization protected."
        }
      ]
    },
    {
      slug: "it-asset-disposition",
      title: "Oakland IT Asset Disposition (ITAD) | Secure IT Asset Disposal Services",
      shortDescription:
        "Professional IT Asset Disposition services for businesses in Oakland. Secure data sanitization, asset recovery, electronics recycling, and compliant IT equipment disposal.",
      icon: "Server",
      metaTitle:
        "IT Asset Disposition (ITAD) Oakland | Secure IT Asset Disposal Services",
      metaDescription:
        "Looking for IT Asset Disposition services in Oakland, CA? IntegriTrade LLC provides secure IT asset disposal, certified data sanitization, asset recovery, and environmentally responsible electronics recycling.",
      image: itAssetDisposition,
      heroHeading: "Oakland Secure IT Asset Disposition Services",
      heroSubheading:
        "Helping Oakland businesses securely retire outdated technology through certified IT asset disposition, data protection, asset recovery, and environmentally responsible disposal solutions.",
      ctaText: "Get a Free Quote",
      details: [
        {
          heading: "Secure Technology Lifecycle Management for Oakland Businesses",
          body:
            "Oakland is one of the Bay Area’s largest business centers, home to healthcare systems, logistics providers, government agencies, educational institutions, financial organizations, technology companies, manufacturers, and professional service firms. These organizations depend on technology infrastructure to support operations, communications, data management, customer service, and long-term growth. As computers, servers, storage systems, networking equipment, and mobile devices reach the end of their useful life, businesses require a secure and compliant strategy for retiring those assets. Professional IT Asset Disposition (ITAD) services help Oakland organizations manage obsolete technology responsibly while protecting sensitive information, maintaining compliance, and supporting sustainability goals."
        },
        {
          heading: "Why Professional ITAD Matters in Oakland",
          body:
            "Technology refresh cycles are essential for improving productivity, strengthening cybersecurity, and supporting business growth. However, retired equipment often contains confidential information including customer records, employee data, financial documents, healthcare information, contracts, intellectual property, and proprietary business communications. Improper disposal can expose organizations to data breaches, legal liability, compliance violations, and reputational harm. A structured IT Asset Disposition program ensures retired technology assets are securely managed while reducing risk and maintaining operational efficiency."
        },
        {
          heading: "Our End-to-End IT Asset Disposition Process",
          body:
            "IntegriTrade LLC provides comprehensive IT Asset Disposition solutions tailored to the needs of Oakland businesses. Our process begins with secure collection and transportation, followed by asset inventory, chain-of-custody tracking, certified data sanitization, asset evaluation, value recovery opportunities, and environmentally responsible disposition. Every asset is documented and managed throughout the process to ensure accountability, transparency, and compliance.",
          bullets: [
            "Secure pickup and transportation",
            "Comprehensive asset inventory and auditing",
            "Chain-of-custody documentation",
            "Certified data sanitization",
            "Asset recovery and remarketing",
            "Environmentally responsible recycling"
          ]
        },
        {
          heading: "What Types of IT Equipment Can Be Processed?",
          body:
            "Our IT Asset Disposition services support a broad range of business technology assets including laptops, desktop computers, servers, storage systems, networking hardware, telecommunications equipment, mobile devices, monitors, printers, engineering workstations, healthcare technology systems, and enterprise infrastructure. Whether your organization is replacing a few devices or conducting a large-scale technology refresh, we provide scalable solutions designed to meet your operational requirements."
        },
        {
          heading: "Reduce Risk and Maximize Asset Value",
          body:
            "Many retired technology assets retain market value long after they are removed from active service. Through our asset recovery and remarketing programs, organizations can recover a portion of their original technology investment while reducing disposal costs. This approach improves return on investment while supporting sustainability goals through equipment reuse and refurbishment. Assets that no longer have recovery value are processed through certified recycling channels to ensure environmentally responsible disposal."
        },
        {
          heading: "Why Choose IntegriTrade LLC for IT Asset Disposition?",
          body:
            "Organizations throughout Oakland trust IntegriTrade LLC because we combine security, compliance, sustainability, and value recovery into one streamlined solution. Our experienced team understands the needs of healthcare providers, logistics companies, government agencies, educational institutions, technology firms, and enterprise businesses. We deliver customized solutions designed to simplify technology retirement while protecting sensitive information.",
          bullets: [
            "Experienced IT asset disposition specialists",
            "Secure chain-of-custody procedures",
            "Certified data destruction capabilities",
            "Detailed reporting and compliance support",
            "Asset recovery and remarketing expertise",
            "Environmentally responsible processing"
          ]
        },
        {
          heading: "Common Questions About IT Asset Disposition",
          body:
            "Find answers to frequently asked questions about IT Asset Disposition services in Oakland.",
          qna: [
            {
              question: "What is IT Asset Disposition (ITAD)?",
              answer:
                "IT Asset Disposition is the secure process of retiring, remarketing, recycling, or disposing of technology assets while protecting sensitive information and maintaining compliance."
            },
            {
              question: "Can retired IT equipment still have value?",
              answer:
                "Yes. Many technology assets retain market value and can be refurbished or remarketed to generate financial returns."
            },
            {
              question: "Do you provide pickup services in Oakland?",
              answer:
                "Yes. We provide secure pickup and transportation services for businesses throughout Oakland and surrounding East Bay communities."
            },
            {
              question: "How is sensitive data protected?",
              answer:
                "All data-bearing devices undergo certified sanitization procedures before assets are remarketed, recycled, or destroyed."
            },
            {
              question: "Do you provide compliance documentation?",
              answer:
                "Yes. We provide detailed asset inventories, chain-of-custody records, reporting, and data destruction documentation when required."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Retiring outdated technology should never compromise your organization's security or compliance. IntegriTrade LLC provides trusted IT Asset Disposition services in Oakland, helping businesses securely manage retired technology assets while maximizing value recovery and supporting sustainability initiatives. Whether you're upgrading systems, refreshing infrastructure, or decommissioning equipment, our team delivers reliable solutions tailored to your organization's needs."
        }
      ]
    },
    {
      slug: "asset-recovery",
      title: "Oakland Asset Recovery | Maximize Value from Retired IT Assets",
      shortDescription:
        "Professional asset recovery services for businesses in Oakland. Recover value from retired IT equipment through secure refurbishment, remarketing, and lifecycle management solutions.",
      icon: "RefreshCcw",
      metaTitle:
        "Asset Recovery Oakland | IT Asset Recovery & Remarketing Services",
      metaDescription:
        "Looking for asset recovery services in Oakland, CA? IntegriTrade LLC helps businesses recover value from retired IT equipment through secure refurbishment, remarketing, and responsible asset management.",
      image: assetRecovery,
      heroHeading: "Oakland Professional Asset Recovery Services",
      heroSubheading:
        "Turn retired technology into measurable business value through secure asset recovery, refurbishment, and remarketing solutions designed for Oakland businesses.",
      ctaText: "Get a Free Quote",
      details: [
        {
          heading: "Recover Maximum Value from Retired Technology Assets",
          body:
            "Technology investments represent a significant operational expense for organizations throughout Oakland. Healthcare providers, logistics companies, government agencies, educational institutions, manufacturers, technology firms, and professional service organizations rely on computers, servers, networking equipment, storage systems, mobile devices, and specialized technology platforms to support daily operations. As equipment reaches the end of its internal lifecycle, many assets continue to retain market value. Without a structured recovery strategy, organizations often miss opportunities to recover capital from retired technology. Professional asset recovery services help organizations maximize financial returns while maintaining security, compliance, and operational efficiency."
        },
        {
          heading: "Why Asset Recovery Matters for Oakland Businesses",
          body:
            "Organizations regularly refresh technology to improve performance, strengthen cybersecurity, support operational efficiency, and maintain competitiveness. However, much of this retired equipment continues to have value in secondary markets. Through professional asset recovery, businesses can offset technology refresh costs, improve return on investment, and reduce unnecessary waste. Asset recovery helps organizations generate value from retired assets while supporting responsible lifecycle management and sustainability objectives."
        },
        {
          heading: "Our Comprehensive Asset Recovery Process",
          body:
            "IntegriTrade LLC provides a transparent and structured asset recovery process designed to maximize financial returns while protecting sensitive information. Every project begins with a detailed inventory and assessment of assets. Equipment is evaluated based on condition, age, specifications, and current market demand. Before any asset enters refurbishment or resale channels, all data-bearing devices undergo certified sanitization procedures to ensure confidential information is permanently removed. This allows organizations to recover value from retired equipment without compromising security or regulatory compliance.",
          bullets: [
            "Comprehensive asset inventory and auditing",
            "Residual value assessment",
            "Certified data sanitization",
            "Equipment refurbishment and testing",
            "Remarketing through qualified sales channels",
            "Detailed recovery and financial reporting"
          ]
        },
        {
          heading: "What Assets Can Be Recovered?",
          body:
            "Many categories of business technology retain value after retirement. We help organizations recover value from laptops, desktop computers, servers, storage systems, networking equipment, telecommunications hardware, healthcare technology systems, manufacturing technology equipment, engineering workstations, monitors, mobile devices, and enterprise infrastructure. Whether your organization is replacing a handful of devices or retiring technology across multiple departments or facilities, our team develops customized recovery strategies designed to maximize financial returns."
        },
        {
          heading: "Supporting Sustainability Through Reuse and Remarketing",
          body:
            "Asset recovery is an important component of sustainable technology lifecycle management. Whenever practical, equipment is refurbished and remarketed instead of being immediately recycled. Extending the useful life of technology assets helps reduce electronic waste, conserve valuable resources, and support a circular economy. Organizations that prioritize asset recovery can strengthen environmental, social, and governance (ESG) initiatives while aligning sustainability objectives with financial performance."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Asset Recovery?",
          body:
            "Organizations throughout Oakland trust IntegriTrade LLC because we combine security, transparency, compliance, and value recovery into one streamlined solution. Our experienced team understands the needs of healthcare providers, logistics companies, government agencies, educational institutions, technology firms, and enterprise businesses. We deliver customized recovery strategies designed to maximize returns while maintaining accountability throughout every phase of the process.",
          bullets: [
            "Experienced asset recovery specialists",
            "Secure chain-of-custody procedures",
            "Certified data destruction capabilities",
            "Transparent reporting and documentation",
            "Established remarketing networks",
            "Environmentally responsible practices"
          ]
        },
        {
          heading: "Common Questions About Asset Recovery",
          body:
            "Find answers to frequently asked questions about asset recovery services in Oakland.",
          qna: [
            {
              question: "What is asset recovery?",
              answer:
                "Asset recovery is the process of identifying, refurbishing, remarketing, and reselling retired technology assets to maximize financial returns while maintaining security and compliance."
            },
            {
              question: "Can retired technology equipment still have value?",
              answer:
                "Yes. Many retired devices retain significant market value depending on their condition, specifications, and demand in secondary markets."
            },
            {
              question: "How is data protected during asset recovery?",
              answer:
                "All data-bearing devices undergo certified sanitization procedures before assets are refurbished, resold, or recycled."
            },
            {
              question: "Do you provide recovery reports?",
              answer:
                "Yes. We provide detailed reporting that outlines recovered assets, financial returns, and overall project results."
            },
            {
              question: "What happens to assets that have no resale value?",
              answer:
                "Equipment with no recovery value is processed through certified recycling channels to ensure environmentally responsible disposal."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Retired technology assets may still represent valuable business resources. IntegriTrade LLC provides professional asset recovery services in Oakland, helping organizations maximize returns from retired equipment while maintaining security, compliance, and sustainability. Whether you're upgrading infrastructure, relocating operations, or retiring outdated technology, our team delivers customized recovery solutions designed to improve return on investment and simplify the asset disposition process."
        }
      ]
    }
  ]
};