import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const petalumaData: ServiceArea = {
  slug: "petaluma",

  name: "Petaluma",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Petaluma, CA",

  metaTitle: "E-Waste Recycling in Petaluma, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Petaluma? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Petaluma, CA, helping enterprises, professional firms, and industrial businesses retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Petaluma E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Petaluma area. We ensure safe, legal, and professional electronics waste disposal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Petaluma | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Petaluma? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Petaluma Premium E-Waste Recycling Solutions",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise in Petaluma, one of the historic and economic centers of Sonoma County and the emerging technology, retail, and dairy industry logistics hub of the North Bay region. As a leading service provider, we ensure that each of your electronic devices is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for Petaluma's traditional and eco-conscious business sector",
          body:
            "The city of Petaluma is known for its historic architecture, eco-friendly agricultural logistics, growing tech startups, and local commercial hubs. Every business and corporate office here needs to constantly upgrade its IT infrastructure and hardware to keep its daily operational mobility and data systems up and running. The massive amount of e-waste generated by this rapid technology refresh, if not properly disposed of, harms the natural beauty of the Petaluma River Basin and Sonoma County. In accordance with California's strict e-waste laws, no commercial enterprise can dispose of its old laptops, servers, networking gear, or monitors in landfills. Our specialized service ensures that harmful lead, cadmium, and mercury are removed from your equipment and the precious metals are recovered for reuse, increasing your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "The security of their customers' personal information (PII), financial records, and confidential corporate data is a top priority for every enterprise in Petaluma. If data is not properly destroyed when recycling old hardware, it can create significant legal complications, corporate compliance violations, and security risks. Violations of e-waste and data protection regulations in California currently require the Department of Toxic Substances Control (DTSC) and CalRecycle to impose stricter regulations and compliance on all electronic devices with built-in or embedded batteries. We follow the NIST 800-88 standard, which is internationally recognized as an extremely safe standard. We also provide an official Certificate of Destruction at the end of each project, which proves that your work was completed in a very safe manner in accordance with California law."
        },
        {
          heading: "Our specialty in corporate IT asset management",
          body:
            "As an experienced service provider, we deeply understand the needs of the local IT market in Petaluma and the logistical challenges of the North Bay region. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure the highest value recovery or ROI of your old assets by refurbishing them. Our specialized process helps you present your business as an 'eco-friendly' brand to investors and conscious customers. By managing e-waste in the right way, on the one hand, the legal and financial risks of your organization are greatly reduced, and system transparency is maintained. We provide customized solutions for everyone, from small professional firms in Petaluma to large commercial and industrial enterprises."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Petaluma Recycling?",
          body:
            "We provide reliable and certified recycling services in the Petaluma area. Every step of our way is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensuring environmentally friendly and safe recycling in accordance with international standards.",
            "Secure Chain of Custody: Every device's serial number is tracked from collection to destruction.",
            "On-Site & Off-Site Facilities: We can provide direct service to your Petaluma office or commercial space, depending on your needs.",
            "Zero Landfill Guarantee: We guarantee that no toxic e-waste will end up in a California landfill.",
            "Detailed Compliance Report: We provide a full report and a destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise-level security. First, we collect the goods from your Petaluma office or data center and prepare a full audit report on them. Then the data carriers (HDD/SSD) from each device are separated and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent to refineries for reuse. At the end of this whole process, we provide you with a final destruction certificate, which ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Frequently asked questions about Petaluma e-waste recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Petaluma, CA.",
          qna: [
            {
              question: "Do you accept personal use electronics (B2C) in Petaluma?",
              answer:
                "We mainly provide enterprise and commercial services. However, at certain times, we provide B2C (business to consumer) services through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Before recycling in our process, the data carrier is shredded in a professional-grade shredder, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the need of the hour in an eco-conscious, historic, and progressive commercial city like Petaluma. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the outdated technology in your office storeroom today and join us in keeping Petaluma's environment cleaner. Our team of experts is always ready to provide customized services for your business. Get your secure recycling quotation today."
        }
      ]
    }
  ]
};