import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const pleasantonData: ServiceArea = {
  slug: "pleasanton",

  name: "Pleasanton",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Pleasanton, CA",

  metaTitle: "E-Waste Recycling in Pleasanton, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Pleasanton? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Pleasanton, CA, helping enterprises, corporate headquarters, and IT innovation centers retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Pleasanton E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Pleasanton area. We ensure safe, legal, and professional electronics waste removal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Pleasanton | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Pleasanton? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Pleasanton Premium E-Waste Recycling Solution",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise in Pleasanton, one of the major economic centers of the Tri-Valley region and home to prestigious corporate headquarters. As a leading service provider, we ensure that each of your electronic devices is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for Pleasanton's corporate and tech district",
          body:
            "The city of Pleasanton is well-known for its well-planned business parks (such as Hacienda Business Park), IT innovation centers, and headquarters of various global organizations. Every business and enterprise here needs to constantly upgrade its IT infrastructure and hardware to keep its data centers and official operations up to date. The huge amount of e-waste generated by this rapid technology refresh, if not properly disposed of, can harm the Tri-Valley region's environment and can have a serious impact on groundwater levels. In accordance with California's strict e-waste laws, no commercial enterprise can dispose of its old laptops, servers, or networking gear in landfills. Our specialized service ensures that harmful lead, cadmium, and mercury are removed from your equipment and valuable materials are recovered for reuse, helping to increase your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "The privacy of their intellectual property (IP) and information is a top priority for every enterprise in Pleasanton. If data is not properly destroyed when recycling old hardware, it can create significant legal complications, corporate compliance violations, and security risks. Currently in California, the Department of Toxic Substances Control (DTSC) imposes strict legal actions and penalties for violating e-waste and data protection regulations. Our industrial-grade data destruction process ensures that each of your storage devices is permanently deleted. We follow the NIST 800-88 standard, an internationally recognized standard. We also provide an official Certificate of Destruction at the end of each project, which proves that your work is done in a highly secure manner, keeping your organization's privacy 100% protected and ready for any audit."
        },
        {
          heading: "Our specialty in corporate IT asset management",
          body:
            "As an experienced service provider, we deeply understand the needs of the local corporate market in Pleasanton and the logistical challenges of large enterprises. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure the highest value recovery or ROI of your old assets through refurbishing. Our specialized process presents your business as an 'eco-friendly' brand to investors and conscious customers. E-waste management in the right way not only protects the environment but also greatly reduces the legal and financial risks of your organization. We provide customized solutions for everyone, from small businesses in Pleasanton to large multinational corporations."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Pleasanton Recycling?",
          body:
            "We provide reliable and certified recycling services in the Pleasanton area. Every step we take is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensuring environmentally friendly and safe recycling in accordance with international standards.",
            "Secure Chain of Custody: Every device's serial number is tracked from collection to destruction.",
            "On-Site & Off-Site Facilities: We can provide direct service to your Pleasanton office or business park as per your needs.",
            "Detailed Compliance Report: We provide a full report and a destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise-level security. First, we collect the goods from your Pleasanton office or data center and prepare a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent to the refinery for reuse. At the end of the process, we provide you with a Final Destruction Certificate, which ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Pleasanton E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Pleasanton, CA.",
          qna: [
            {
              question: "Do you accept personal use electronics (B2C) in Pleasanton?",
              answer:
                "We mainly provide enterprise and commercial services. However, at certain times, we provide B2C (business to consumer) services through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial-grade shredders before recycling in our process, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the need of the hour in a well-established and sustainable economic city like Pleasanton. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the old technologies piling up in your office storeroom today and join us in making Pleasanton's environment cleaner. Our expert team is always ready to provide customized services tailored to your business needs. Collect your secure recycling quotation today."
        }
      ]
    }
  ]
};