import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const sacramentoData: ServiceArea = {
  slug: "sacramento",

  name: "Sacramento",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Sacramento, CA",

  metaTitle: "E-Waste Recycling in Sacramento, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Sacramento? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Sacramento, CA, helping enterprises, government offices, and large healthcare networks retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Sacramento E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Sacramento area. We ensure safe, legal, and professional electronics waste removal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Sacramento | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Sacramento? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Sacramento Premium E-Waste Recycling Solution",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise in the city of Sacramento, the capital of California and one of the main political, administrative and economic centers. As a leading service provider, we ensure that each of your electronic equipment is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for Sacramento's public, institutional and corporate sectors",
          body:
            "As the capital of California, the city of Sacramento is home to numerous government offices, corporate headquarters, large healthcare networks, and the driving force behind fast-growing technology companies. Every business, legal entity, and commercial organization here needs to constantly upgrade IT infrastructure and hardware to keep their day-to-day administrative and data systems up and running. The huge amount of e-waste generated by this rapid technology refresh, if not properly disposed of, could end up in the Sacramento River. In accordance with California's strict e-waste laws, no commercial enterprise can dispose of its old laptops, servers, networking gear, or monitors in landfills. Our specialized service ensures that harmful lead, cadmium, and mercury are removed from your organization's equipment and the precious metals are recovered for reuse, helping to increase your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "Corporate data security is a top priority for every enterprise in Sacramento. If data is not properly destroyed when recycling old hardware, it can create significant legal complications, corporate compliance violations, and security risks. Violations of e-waste and data protection regulations in California are currently subject to strict legal action and daily fines by the Department of Toxic Substances Control (DTSC) and CalRecycle. Stricter regulations apply to all electronic devices with built-in or embedded batteries. We follow the NIST 800-88 standard, an internationally recognized standard, and provide an official Certificate of Destruction at the end of each project, which proves that your work has been done in a highly secure manner in accordance with California law."
        },
        {
          heading: "Our specialty in corporate IT asset management",
          body:
            "As an experienced service provider, we deeply understand the needs of the local IT market in Sacramento and the logistics challenges of the capital region. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure the highest value recovery or ROI of your old assets by refurbishing them. Our specialized process helps you present your business as an 'eco-friendly' brand to investors and conscious customers. By managing e-waste in the right way, on the one hand, your organization's legal and financial risks are greatly reduced, and system transparency is maintained. We provide customized solutions for everyone, from small professional firms in Sacramento to large commercial and government enterprises."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Sacramento Recycling?",
          body:
            "We provide reliable and certified recycling services in the Sacramento area. Every step we take is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensuring environmentally friendly and safe recycling in accordance with international standards.",
            "Secure Chain of Custody: Every device's serial number is tracked from collection to destruction.",
            "On-Site & Off-Site Facilities: We can visit your Sacramento office or commercial space to serve you directly, depending on your needs.",
            "Detailed Compliance Report: We provide a full report and a destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise-level security. First, we collect the goods from your Sacramento office or data center and prepare a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent to refineries for reuse. At the end of this entire process we provide you with a Final Destruction Certificate which ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Sacramento E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Sacramento, CA.",
          qna: [
            {
              question: "Do you accept personal use electronics (B2C) in Sacramento?",
              answer:
                "We mainly provide enterprise and commercial services. However, at certain times we provide B2C (business to consumer) services through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial grade shredders before recycling in our process and we provide guarantee certificate for this which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the call of the hour in a politically progressive and dynamic commercial city like Sacramento. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC provides you with the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the old technologies piling up in your office storeroom today and join us to keep Sacramento's environment cleaner. Our expert team is always ready to provide customized services tailored to your business needs. Collect your secure recycling quotation today."
        }
      ]
    }
  ]
};