import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const sanBrunoData: ServiceArea = {
  slug: "san-bruno",

  name: "San Bruno",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in San Bruno, CA",

  metaTitle: "E-Waste Recycling in San Bruno, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in San Bruno? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in San Bruno, CA, helping enterprises, tech companies, and corporate offices retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "San Bruno E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the San Bruno area. We ensure safe, legal, and professional disposal of electronic waste.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling San Bruno | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in San Bruno? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "San Bruno Premium E-Waste Recycling Solution",

      heroSubheading:
        "We offer reliable e-waste solutions for your enterprise in San Bruno, one of the most important hubs of digital media and global technology. As a leading service provider, we guarantee to recycle each of your electronic equipment in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for San Bruno businesses",
          body:
            "The city of San Bruno is well known for its presence of world-renowned digital platforms and leading corporate offices. Every business and startup here needs to continually upgrade its IT infrastructure to stay ahead of the digital landscape. The large amount of e-waste generated by this rapid technology refresh can have a serious impact on the local environment of the Peninsula region if not disposed of properly. According to California's strict e-waste laws, any commercial organization cannot dispose of their old laptops, servers, or networking gear in landfills with general trash. Our specialized service ensures that harmful lead and mercury are removed from your organization's equipment and precious metals are recovered for reuse, helping to increase your brand's social and environmental responsibility."
        },
        {
          heading: "Ensuring Secure Data Destruction and Legal Compliance",
          body:
            "Digital security and data privacy are top priorities for every enterprise in San Bruno. If data is not properly destroyed when recycling old hardware, it can create major legal complications and security risks. Our industrial-grade data destruction process ensures that data on each of your storage devices is permanently erased. We follow the NIST 800-88 standard, an internationally recognized, highly secure standard. We also provide an official Certificate of Destruction, which proves that your work has been done very securely in accordance with California law. It keeps your organization's confidentiality 100% protected, and you are always prepared for any audit."
        },
        {
          heading: "Our role in corporate e-waste management",
          body:
            "As an experienced service provider, we deeply understand the needs of the local IT market in San Bruno and the challenges faced by tech companies. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure the highest value recovery or ROI of your old assets by refurbishing them. Our specialized process helps you present your business as an 'eco-friendly' brand to investors. Managing e-waste the right way not only protects the environment but also greatly reduces your organization's legal and financial risks and maintains system transparency. We provide customized solutions for everyone, from small startups to large corporations, in San Bruno."
        },
        {
          heading: "Why Choose IntegriTrade LLC for San Bruno Recycling?",
          body:
            "We provide reliable and certified recycling services in the San Bruno area. Every step of our way is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensures environmentally friendly and safe recycling as per international standards.",
            "Secure Chain of Custody: The serial number of each device is tracked from the time of collection until destruction.",
            "On-Site and Off-Site Facilities: We can also visit your San Bruno office directly to serve you as per your needs.",
            "Zero Landfill Guarantee: We guarantee that no toxic e-waste will end up polluting a California landfill.",
            "Detailed Compliance Report: We provide full reports and certificates for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process (Process)",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise-level security. First, we collect the goods from your San Bruno office or data center and prepare a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent to refineries for reuse. At the end of this whole process, we provide you with a final destruction certificate, which ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About San Bruno E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in San Bruno, CA.",
          qna: [
            {
              question: "Do you accept personal use of electronics (B2C) in San Bruno?",
              answer:
                "We primarily serve at the enterprise and commercial levels. However, at certain times, we provide B2C (business to consumer) service through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial-grade shredders before recycling in our process, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the call of the hour in a technology and media-driven city like San Bruno. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the outdated technology in your office storeroom today and join us in keeping San Bruno's environment cleaner. Our team of experts is always ready to provide customized services as per your business needs. Collect your secure recycling quotation today and move towards a sustainable future."
        }
      ]
    }
  ]
};