import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const santaRosaData: ServiceArea = {
  slug: "santa-rosa",

  name: "Santa Rosa",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Santa Rosa, CA",

  metaTitle: "E-Waste Recycling in Santa Rosa, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Santa Rosa? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Santa Rosa, CA, helping enterprises, healthcare organizations, and technology institutes retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Santa Rosa E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Santa Rosa area. We ensure safe, legal, and professional electronics waste removal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Santa Rosa | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Santa Rosa? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Santa Rosa Premium E-Waste Recycling Solutions",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise in Santa Rosa, Sonoma County's largest city and the North Bay region's main commercial, technology, and wine industry logistics hub. As a leading service provider, we ensure that each of your electronic devices is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "E-Waste Management for Sustainable and Eco-Conscious Businesses in Santa Rosa",
          body:
            "The city of Santa Rosa is known for its beautiful natural environment, winery logistics, growing medical sector, and technology institutes. Every business and enterprise here needs to constantly upgrade its IT infrastructure and hardware to keep its official operations and data systems up and running. The massive amount of e-waste generated by this rapid technology refresh, if not disposed of properly, can have a serious impact on Sonoma County's beautiful natural environment and groundwater levels. California's strict e-waste laws require that no commercial organization can dispose of their old laptops, servers, networking gear, or monitors in landfills with general garbage. Our specialized service ensures that harmful lead and mercury are removed from your organization's equipment and valuable metals are recovered for reuse, helping to increase your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "Corporate data security is a top priority for every enterprise in Santa Rosa. If data is not properly destroyed when recycling old hardware, it can create major legal complications, corporate compliance violations, and security risks. Violations of e-waste and data protection regulations in California are currently subject to strict legal steps and fines by the Department of Toxic Substances Control (DTSC) and CalRecycle. Stricter rules apply to all electronic devices with built-in or embedded batteries. We follow the NIST 800-88 standard, an internationally recognized standard. We also provide an official Certificate of Destruction at the end of each project, which demonstrates that your work has been performed in a highly secure manner in accordance with California law."
        },
        {
          heading: "Our specialty in corporate IT asset management",
          body:
            "As an experienced service provider, we deeply understand the needs of the local IT market in Santa Rosa and the logistics challenges of the North Bay region. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure the highest value recovery or ROI of your old assets through refurbishing. Our specialized process presents your business as an 'eco-friendly' brand to investors and conscious customers. E-waste management in the right way not only protects the environment but also greatly reduces the legal and financial risks of your organization. We provide customized solutions for everyone, from small professional firms in Santa Rosa to large commercial and healthcare enterprises."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Santa Rosa Recycling?",
          body:
            "We provide reliable and certified recycling services in the Santa Rosa area. Every step we take is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensuring environmentally friendly and safe recycling in accordance with international standards.",
            "Secure Chain of Custody: Every device's serial number is tracked from collection to destruction.",
            "On-Site & Off-Site Facilities: We can provide direct service to your Santa Rosa office or commercial space, depending on your needs.",
            "Zero Landfill Guarantee: We guarantee that no toxic e-waste will end up in a California landfill.",
            "Detailed Compliance Report: We provide full report and a destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process",
          body:
            "Our work process is very orderly and transparent which is mainly designed for enterprise level security. First we collect the goods from your Santa Rosa office or data center and prepare a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass and metal components. Finally, precious metals such as copper and gold are sent to refineries for reuse. At the end of this whole process we provide you with a final destruction certificate which ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Santa Rosa E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Santa Rosa, CA.",
          qna: [
            {
              question: "Do you accept personal use of electronics (B2C) in Santa Rosa?",
              answer:
                "We mainly provide enterprise and commercial services. However, at certain times, we provide B2C (business to consumer) services through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial-grade shredders before recycling in our process, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the call of the hour in an eco-conscious and progressive commercial city like Santa Rosa. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the outdated technology in your office storeroom today and join us in making Santa Rosa's environment cleaner. Our expert team is always ready to provide customized services according to your business needs. Collect your secure recycling quotation today."
        }
      ]
    }
  ]
};