import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const stocktonData: ServiceArea = {
  slug: "stockton",

  name: "Stockton",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Stockton, CA",

  metaTitle: "E-Waste Recycling in Stockton, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Stockton? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Stockton, CA, helping enterprises, shipping companies, and supply chain distribution centers retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Stockton E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Stockton area. We ensure safe, legal, and professional electronics waste removal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Stockton | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Stockton? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Stockton Premium E-Waste Recycling Solution",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise in Stockton, San Joaquin County's premier logistics and inland port hub, a fast-growing commercial hub. As a leading service provider, we ensure that each of your electronic equipment is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for Stockton's logistics, manufacturing and corporate sectors",
          body:
            "The city of Stockton is one of the region's major economic engines due to its strategic location in California's Central Valley, deep-water port (Inland Port), and extensive manufacturing and logistics network. Every business, shipping enterprise, and commercial supply chain distribution center here requires constant IT infrastructure and technical hardware upgrades to maintain their operational efficiency. When the large amount of e-waste generated by this rapid technology refresh is not disposed of properly, it can have a serious impact on the Delta region and the overall Valley environment. In accordance with California's strict e-waste laws, no commercial enterprise can dispose of their old laptops, servers, networking gear, or monitors in the landfill with general garbage. Our specialized service ensures that harmful lead, cadmium, and mercury are removed from your equipment and valuable metals are recovered for reuse, helping to increase your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "Corporate data security is a top priority for every enterprise in Stockton. If data is not properly destroyed when recycling old hardware, it can create major legal complications, corporate compliance violations, and security risks. California's Department of Toxic Substances Control (DTSC) and CalRecycle currently impose strict legal steps and frequent fines for violating e-waste and data protection regulations. Stricter rules apply to all electronic devices with built-in or embedded batteries. We follow the NIST 800-88 standard, an internationally recognized standard, and provide an official Certificate of Destruction at the end of each project, which proves that your work has been done in a highly secure manner in accordance with California law."
        },
        {
          heading: "Corporate IT Asset Management and Value Recovery",
          body:
            "As an experienced service provider, we deeply understand the local IT market needs and logistical challenges in Stockton. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure the highest value recovery or ROI of your old assets by refurbishing them. Our specialized process helps you present your business as an 'eco-friendly' brand to investors and conscious customers. E-waste management in the right way not only protects the environment but also greatly reduces your organization's legal and financial risks and maintains system transparency. We provide customized solutions for everyone, from small professional firms in Stockton to large commercial and industrial enterprises."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Stockton Recycling?",
          body:
            "We provide reliable and certified recycling services in the Stockton area. Every step of our way is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensuring environmentally friendly and safe recycling in accordance with international standards.",
            "Secure Chain of Custody: Every device's serial number is tracked from collection to destruction.",
            "On-Site & Off-Site Facilities: We can provide direct service to your Stockton office or commercial space, depending on your needs.",
            "Zero Landfill Guarantee: We guarantee that no toxic e-waste will end up in a California landfill.",
            "Detailed Compliance Report: We provide a full report and destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise level security. First we collect the goods from your Stockton office or logistics center and prepare a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass and metal components. Finally, precious metals such as copper and gold are sent to refineries for reuse. At the end of the entire process, we provide you with a final destruction certificate that ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Stockton E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Stockton, CA.",
          qna: [
            {
              question: "Do you accept personal use electronics (B2C) in Stockton?",
              answer:
                "We mainly provide enterprise and commercial services. However, at certain times, we provide B2C (business to consumer) services through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial-grade shredders before recycling in our process, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the need of the hour in an important logistics hub and thriving commercial city like Stockton. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the old technologies in your office storeroom today and join us in keeping Stockton's environment cleaner. Our expert team is always ready to provide customized services according to your business needs. Collect your secure recycling quotation today."
        }
      ]
    }
  ]
};