import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const visaliaData: ServiceArea = {
  slug: "visalia",

  name: "Visalia",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Visalia, CA",

  metaTitle: "E-Waste Recycling in Visalia, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Visalia? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Visalia, CA, helping enterprises, distribution centers, and agri-business companies retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Visalia E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Visalia area. We ensure safe, legal, and professional electronics waste removal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Visalia | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Visalia? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Visalia Premium E-Waste Recycling Solution",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise in Visalia, Tulare County's economic driving force, agricultural processing and growing commercial distribution hub. As a leading service provider, we ensure that each of your electronic equipment is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for Visalia's distribution, light manufacturing and agri-business sectors",
          body:
            "Visalia, one of the key strategic cities in the Central Valley, is well known for its strong logistics network, manufacturing industry and huge agricultural trade. Every business, distribution center and corporate office here has to constantly upgrade IT infrastructure, servers, computers and networking hardware to keep their supply chain and operational efficiency up. The huge amount of e-waste generated by this rapid technology refresh, if not properly disposed of, can seriously harm the region's environment. In accordance with California's strict e-waste laws, no commercial company can dispose of its old laptops, servers, networking gear, or monitors in landfills. Our specialized service ensures that harmful lead, mercury, and other toxic elements are removed from your company's equipment and the valuable metals are recovered for reuse, helping to increase your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "Corporate data security and information privacy are top priorities for every enterprise in Visalia. If data is not properly destroyed when recycling old hardware, it can create significant legal complications, corporate compliance violations, and security risks. Violations of e-waste and data protection regulations in California are currently enforced by the Department of Toxic Substances Control (DTSC) and CalRecycle. Stricter legal action and fines apply daily, especially to all electronic devices with built-in or embedded batteries. We follow the NIST 800-88 standard, an internationally recognized standard, and provide an official Certificate of Destruction, which proves that your work was done in a highly secure manner in accordance with California law."
        },
        {
          heading: "Corporate IT Asset Management and Value Recovery",
          body:
            "As an experienced service provider, we deeply understand the needs of the local IT market in Visalia and the logistics challenges of Tulare County. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure maximum value recovery or ROI of your old assets through refurbishing. Our specialized process presents your business as an 'eco-friendly' brand to investors and conscious customers. On the one hand, e-waste management protects the environment; on the other hand, the legal and financial risks of your organization are greatly reduced, and the transparency of the system is maintained. We provide customized solutions for everyone, from small professional firms to large commercial and distribution enterprises."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Visalia Recycling?",
          body:
            "We provide reliable and certified recycling services in the Visalia area. Every step of our way is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensures environmentally friendly and safe recycling as per international standards.",
            "Secure Chain of Custody: The serial number of each device is tracked from the time of collection until destruction.",
            "On-Site and Off-Site Facilities: We can provide direct service to your Visalia office or commercial space as per your requirement.",
            "Zero Landfill Guarantee: We guarantee that no toxic e-waste will end up in a California landfill.",
            "Detailed Compliance Report: We provide a full report and a destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise-level security. First, we collect the goods from your Visalia office or logistics center and prepare a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent to the refinery for reuse. At the end of this whole process, we provide you with a final destruction certificate, which ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions on Visalia E-waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Visalia, CA.",
          qna: [
            {
              question: "Do you accept personal use electronics (B2C) in Visalia?",
              answer:
                "We primarily serve at the enterprise and commercial levels. However, at certain times, we provide B2C (business to consumer) service through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial-grade shredders before recycling in our process, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the need of the hour in an important commercial and distribution hub and dynamic manufacturing city like Visalia. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the old technologies in your office storeroom today and join us to keep Visalia's environment cleaner. Our expert team is always ready to provide customized services according to your business needs. Get your secure recycling quotation today."
        }
      ]
    }
  ]
};