import { ServiceArea } from "./types/serviceAreaTypes";
import hardDriveShredding from "@/public/services/serviceArea/driveShredding.jpeg";
import dataDestruction from "@/public/services/serviceArea/dataDestruction.png";
import itAssetDisposition from "@/public/services/serviceArea/itAssetDisposition(ITAD).jpeg";
import electronicRecycling from "@/public/services/serviceArea/electronicRecycling.jpeg";
import assetRecovery from "@/public/services/serviceArea/assetRecovery.png";

export const walnutCreekData: ServiceArea = {
  slug: "walnut-creek",

  name: "Walnut Creek",

  tagline: "Certified Electronics Disposal, Secure Data Destruction & Corporate IT Asset Management in Walnut Creek, CA",

  metaTitle: "E-Waste Recycling in Walnut Creek, CA | Trusted Corporate E-Waste Recycling",

  metaDescription: "Looking for e-waste recycling in Walnut Creek? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

  intro: "IntegriTrade LLC delivers certified electronics disposal and IT asset management services in Walnut Creek, CA, helping enterprises, commercial offices, and healthcare networks retire outdated technology with confidence. Our offerings cover secure data destruction, hard drive shredding, sustainable electronics processing, and asset value recovery to maximize returns from legacy devices. Every engagement is backed by full regulatory compliance, tracked chain-of-custody handling, and environmentally responsible disposal tailored to your organization's needs.",

  services: [
    {
      slug: "e-waste-recycling",
      title: "Walnut Creek E-Waste Recycling | Corporate IT Asset Management",
      shortDescription:
        "Certified e-waste recycling for businesses in the Walnut Creek area. We ensure safe, legal, and professional electronics waste disposal.",
      icon: "Monitor",

      metaTitle:
        "E-waste Recycling Walnut Creek | Safe and Certified E-waste Recycling",

      metaDescription:
        "Looking for e-waste recycling in Walnut Creek? IntegriTrade LLC provides secure data destruction and environmentally friendly electronics recycling services in compliance with California law.",

      image: electronicRecycling,

      heroHeading:
        "Walnut Creek Premium E-Waste Recycling Solution",

      heroSubheading:
        "We provide reliable e-waste solutions for your enterprise in Walnut Creek, one of the premier business, professional and medical services hubs in the East Bay region. As a leading service provider, we ensure that each of your electronic equipment is recycled in an environmentally friendly and legal manner.",

      ctaText: "Get a Free Quote",

      details: [
        {
          heading: "Sustainable e-waste management for the corporate and healthcare sectors in Walnut Creek",
          body:
            "The city of Walnut Creek is well-known for its high quality of life, prestigious corporate offices, retail centers and major healthcare networks (such as John Muir Health). Every business and commercial organization here needs to constantly refresh their IT infrastructure and hardware to keep their operational mobility and data systems up-to-date. The large amount of e-waste generated by this rapid change, if not properly disposed of, can harm the local environment and Mount Diablo. In accordance with California's strict e-waste laws, no commercial enterprise can dispose of its old laptops, servers, medical monitors, or networking gear in landfills. Our specialized service ensures that harmful toxic chemicals are removed from your organization's equipment and valuable metals are recovered for reuse, increasing your brand's social and environmental responsibility."
        },
        {
          heading: "Secure Data Destruction and California Legal Compliance",
          body:
            "The privacy of customers' personal information (PII), financial records, and healthcare data is a top priority for every Walnut Creek enterprise. If data is not properly destroyed when recycling old hardware, it can create significant legal complications, global compliance violations and security risks. Violations of e-waste and data protection regulations in California currently result in the Department of Toxic Substances Control (DTSC) and CalRecycle imposing stricter legal measures and penalties, especially for electronic devices with built-in or embedded batteries. We follow the NIST 800-88 standard, an internationally recognized standard, and at the end of every project issue a Certificate of Destruction, which proves that your work was done in a highly secure manner in accordance with California law."
        },
        {
          heading: "Our specialty in corporate IT asset management",
          body:
            "As an experienced service provider, we deeply understand the needs of the local IT market in Walnut Creek and the logistical challenges of business parks and offices. Our goal is to offer a transparent and efficient recycling process by reducing the logistical hassles of businesses. We not only remove waste, but also help ensure the highest value recovery or ROI of your old assets through refurbishing. Our specialized process helps present your business as an 'eco-friendly' brand to investors and conscious customers. On the one hand, e-waste management protects the environment, and on the other hand, your organization's legal and financial risks are greatly reduced and system transparency is maintained. We provide customized solutions for everyone, from small professional firms in Walnut Creek to large medical enterprises."
        },
        {
          heading: "Why Choose IntegriTrade LLC for Walnut Creek Recycling?",
          body:
            "We provide reliable and certified recycling services in the Walnut Creek area. Every step we take is designed with your business needs and California environmental laws in mind. Below are our specialties:",
          bullets: [
            "R2v3 Certified Process: Ensuring environmentally friendly and safe recycling in accordance with international standards.",
            "Secure Chain of Custody: Every device's serial number is tracked from collection to destruction.",
            "On-Site & Off-Site Facilities: We can provide services directly to your Walnut Creek office or clinic, depending on your needs.",
            "Detailed Compliance Report: We provide a full report and destruction certificate for audit and tax benefits."
          ]
        },
        {
          heading: "Our Advanced Work Process",
          body:
            "Our work process is very orderly and transparent, which is mainly designed for enterprise-level security. First, we collect the goods from your Walnut Creek office or data center and prepare a full audit report on them. Then the data carriers (HDD/SSD) are separated from each device and physically crushed. The remaining parts are broken down into plastic, glass, and metal components. Finally, precious metals such as copper and gold are sent to refineries for reuse. At the end of this whole process, we provide you with a final destruction certificate, which ensures the legal protection of your organization and maintains full transparency of every step of your asset management."
        },
        {
          heading: "Common Questions About Walnut Creek E-Waste Recycling",
          body:
            "Find answers to frequently asked questions about certified electronics disposal, secure data destruction, and corporate IT asset management services in Walnut Creek, CA.",
          qna: [
            {
              question: "Do you accept personal use electronics (B2C) in Walnut Creek?",
              answer:
                "We mainly provide enterprise and commercial services. However, at certain times, we provide B2C (business to consumer) services through special events where individual devices can be submitted."
            },
            {
              question: "Is there a risk of data theft during recycling?",
              answer:
                "Absolutely not. Data carriers are shredded in industrial-grade shredders before recycling in our process, and we provide a guarantee certificate for this, which ensures maximum security of your data."
            }
          ]
        },
        {
          heading: "Conclusion",
          body:
            "Responsible e-waste management is the call of the hour in a well-established, modern and eco-conscious commercial city like Walnut Creek. By choosing the right service provider, you can play a big role in protecting your organization's data as well as protecting the environment. IntegriTrade LLC offers you the safest and most efficient commercial recycling solutions in compliance with California regulations. Get rid of the old technology piled up in your office storeroom today and join us in keeping Walnut Creek's environment cleaner. Our expert team is always ready to provide customized services according to your business needs. Get your secure recycling quotation today."
        }
      ]
    }
  ]
};