export const siteConfig = {
  url: "https://integritradellc.com",
  title: "Integritrade LLC | Secure ITAD & E-Waste Recycling",
  description:
    "Integritrade LLC provides secure, compliant, and environmentally responsible IT asset disposition (ITAD) and electronic recycling services for businesses of all sizes. Certified in R2v3, ISO 9001, ISO 14001, and ISO 27001 standards.",
  keywords: [
    "ITAD",
    "IT asset disposition",
    "electronic recycling",
    "data destruction",
    "e-waste recycling",
    "secure IT recycling",
    "IT equipment disposal",
    "Integritrade LLC",
    "IT asset recovery",
    "electronics recycling Fresno",
  ],
  siteName: "Integritrade LLC",
  business: {
    name: "Integritrade LLC",
    type: "LocalBusiness",
    url: "https://integritradellc.com",
    logo: "https://integritradellc.com/_next/static/media/main-logo.d956176c.png", 
    image: "https://integritradellc.com/_next/static/media/main-logo.d956176c.png", 
    telephone: "+1-559-325-4813",
    email: "info@integritradeLLC.com",
    address: {
      streetAddress: "1945 N Fine Ave, STE 111",
      addressLocality: "Fresno",
      addressRegion: "CA",
      postalCode: "93727",
      addressCountry: "US",
    },
  },
};
