// GENERATED by scripts/build-read-times.mjs — do not edit by hand.
// Reading time in minutes, derived from each article's word count at 225 wpm.
// Re-run after adding or editing a post: node scripts/build-read-times.mjs

export const blogReadTimes: Record<string, number> = {
  "ai-trends-in-it-refresh-hardware-recovery": 7,
  "bay-area-itad-electronics-recycling": 7,
  "bfsi-it-asset-disposition-financial-services-data-destruction": 11,
  "chain-of-custody-in-itad": 5,
  "cod-vs-coe-data-destruction-certification-services": 6,
  "data-erasure-vs-degaussing-vs-physical-destruction": 6,
  "data-sanitization-best-practices-itad": 10,
  "deceptive-advertising-itad-electronics-recycling-certifications": 12,
  "decommission-old-computers-it-equipment": 8,
  "fair-flexible-itad-cutlines": 6,
  "ferpa-school-it-asset-disposition-chromebook-recycling-student-data-destruction": 10,
  "hipaa-compliant-itad-data-destruction-services": 5,
  "how-to-assess-electronics-recycling-it-asset-disposal-provider": 13,
  "is-it-possible-to-recover-deleted-data": 6,
  "it-asset-disposition-explained": 6,
  "it-asset-disposition-fresno-ca": 7,
  "it-asset-disposition-sacramento-ca": 7,
  "it-asset-recovery-process-and-best-practices": 8,
  "it-asset-recovery-services-maximize-value": 8,
  "it-equipment-depreciation-and-risks": 6,
  "itad-compliance-and-data-destruction-policies": 9,
  "itad-cutlines-asset-recovery-value-services": 6,
  "itad-cutlines-revenue-sharing-devices": 8,
  "itad-vs-e-waste-recycling": 7,
  "itad-vs-free-e-waste-recycling-risks": 7,
  "landfill-vs-certified-recycling-environment": 6,
  "law-firm-it-asset-disposition-legal-data-destruction": 11,
  "nist-800-88-rev-2-clear-purge-destroy": 13,
  "nvme-data-destruction-methods": 7,
  "r2-certified-e-waste-recycling-services": 7,
  "remove-apple-dep-mdm-lock-devices": 8,
  "reuse-focused-itad-vs-scrap-recycling": 11,
  "risk-of-storing-old-hard-drives-vs-recycling": 5,
  "rohs-compliance-electronics-recycling-services": 7,
  "server-data-center-equipment-disposal-guide": 6,
  "video-tape-data-destruction-services": 7,
  "what-is-itad-it-asset-disposition": 8,
  "why-it-asset-disposition-is-important": 7,
  "zero-trust-security-in-it-asset-disposition": 6,
};

/** Minutes for a slug, or null when the post has no generated entry yet. */
export function readTimeFor(slug: string): number | null {
  return blogReadTimes[slug] ?? null;
}
